### ISSUE TITLE
mt-element报错

### ISSUE THREAD

**Issue by 1itttlesheep** [windsound3482/Kommentar-App#11]
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <MtButton>
       <Login> at src/components/login/login.vue
         <Account> at src/views/Account.vue
           <ElHeader> at packages/header/src/main.vue
             <ElContainer> at packages/container/src/main.vue
               <App> at src/App.vue
                 <Root>

**Comment by windsound3482** [comment]
You have use mint@1 instead mint@2.....
