### ISSUE TITLE
Login information cannot be synchronized

### ISSUE THREAD

**Issue by elaineJJY** [windsound3482/Kommentar-App#4]
**Login information cannot be synchronized. As a result, the display of components in the Account.vue cannot be switched.**
Ideal state:
logged:  Component<accounticon> will show （v-show   logged=true） 
not logged: Component<login> and <register> will show（v-show   logged=true）

**Comment by windsound3482** [comment]
issue fixed , detail please check jldev/issuefix

it is because you shoule call state.(modulename).(parameter name) while you use state in a module

and please use computed instead of watched in programming in order to speed up
